language: clojure
lein: lein
dist: trusty

script: lein do clean, compile :all, test, doo phantom test once

deploy:
  - provider: script
    skip_cleanup: true
    script: ./script/ci-release.sh
    jdk: openjdk11
    if: branch = master

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk11
